"""add aws credentials to project

Revision ID: ead2583b604d
Revises: e1b0d4c3f9a1
Create Date: 2026-03-07 02:02:48.517258

"""
from typing import Sequence, Union
from uuid import UUID

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead2583b604d'
down_revision: Union[str, None] = 'e1b0d4c3f9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('aws_access_key_id', sa.String(length=128), nullable=True))
    op.add_column('projects', sa.Column('aws_secret_access_key', sa.String(length=128), nullable=True))
    op.add_column('projects', sa.Column('aws_region', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'aws_region')
    op.drop_column('projects', 'aws_secret_access_key')
    op.drop_column('projects', 'aws_access_key_id')
    # ### end Alembic commands ###
